### ISSUE TITLE
Ask some problems about code

### ISSUE THREAD

**Issue by user-yifanjiang** [exporl/spatial-focus-of-attention-csp#2]
I read your paper about Fast EEG-based decoding of the directional focus of auditory attention using common spatial patterns recently,I was very inspired.But I encountered the following problems in the reproduction program, I hope to get your answer.
1.How to definition of eegtrials,attendedEar in program loadData.m 
2.What the value of fs in mainSubjrctSpecific.m program

**Comment by sgeirnae** [comment]
Hi Yifan,

1. The eegTrials are defined as a cell with the different EEG trials, containing matrices (time x channels). attendedEar is defined as a vector containing the labels (e.g., left-right attended), coded with '1' and '2'. For an example: see the dataset we published on Zenodo.
2. The sampling frequency is defined as output of the loadData.m-function and depends on your dataset.
